//! # RWA Compliance Flow Integration
//!
//! An integration example demonstrating how the three compliance primitives
//! compose to form a comprehensive compliance framework for RWA tokens and stablecoins.
//!
//! ## Pattern: Policy Composition via Trait-Based Clients
//!
//! This example shows a **lightweight integration layer** that does not implement
//! a token itself. Instead, it defines trait-based clients for the three primitives
//! and demonstrates the canonical composition pattern:
//!
//! 1. Each primitive (allowlist, denylist, jurisdiction) is wired independently
//! 2. Calls are made in series (AND logic); all must pass for a transfer to succeed
//! 3. Specific error types are returned to identify which check failed
//!
//! ## Compliance Layers Demonstrated
//!
//! - **Allowlist**: Only allowlisted addresses can transact
//! - **Denylist**: Sanctioned, defrauded, or court-ordered addresses are blocked
//! - **Jurisdiction**: Restricts activity to permitted jurisdictions (e.g., regulatory
//!   requirements)
//!
//! ## Differences from other examples
//!
//! - **vs. `/examples/rwa-token`**: That crate implements a complete token contract with
//!   balance tracking and integration of all three gates. This module shows only the
//!   compliance composition pattern without the token implementation.
//! - **vs. `/examples/denylist-gate-sep41`**: That crate is a SEP-41 token gated by
//!   denylist-gate alone. This demonstrates composition of all three gates.
//!
//! ## Test Coverage
//!
//! The module includes comprehensive tests verifying:
//! 1. A successful transfer when all three compliance checks pass
//! 2. Blocked transfers when each compliance check independently fails
//!
//! ## Two Compliance Abstractions in This Workspace (issue #414)
//!
//! This example defines [`CrossContractComplianceCheck`] (previously named
//! `ComplianceCheckInterface`) — a `#[contractclient]`-backed trait for
//! **runtime cross-contract XDR calls** between deployed Soroban contracts.
//!
//! The workspace also contains `contracts/compliance-check`, which defines
//! the plain Rust [`ComplianceCheck`][cc] trait for **compile-time composition**
//! (unit tests, generic helpers, same-crate callers).
//!
//! | Abstraction | Where | Mechanism | Use case |
//! |---|---|---|---|
//! | `compliance_check::ComplianceCheck` | `contracts/compliance-check` | Plain Rust trait | Compile-time: unit tests, generic helpers |
//! | [`CrossContractComplianceCheck`] (this file) | `examples/rwa-compliance-flow` | `#[contractclient]` macro | Runtime: deployed contract → deployed contract XDR calls |
//!
//! **Why two?** Soroban's `#[contractclient]` macro generates XDR encoding/
//! decoding stubs that work for cross-contract invocations on the host but
//! cannot be used for Rust generics or compile-time composition.  The plain
//! Rust trait covers that use case without any XDR overhead.  The two serve
//! different layers of the stack and are both necessary — they are not
//! duplicates.
//!
//! [`CrossContractComplianceCheck`]: CrossContractComplianceCheck
//! [cc]: ../../../contracts/compliance-check/src/lib.rs

#![no_std]

use soroban_sdk::{Address, Env, String};

// Contract clients generated from trait definitions.
// These allow us to call the three compliance contracts without linking their
// full implementations — using Soroban XDR-based cross-contract invocations.
use soroban_sdk::contractclient;

/// Cross-contract compliance check interface for **runtime** XDR-based calls.
///
/// Generated by the `#[contractclient]` macro into `CrossContractComplianceCheckClient`,
/// this trait describes the `is_compliant(address) -> bool` entry point that all
/// three compliance primitives expose on-chain.  Use the generated
/// `CrossContractComplianceCheckClient` to call any deployed compliance contract
/// from another deployed contract at runtime.
///
/// ## Difference from `compliance_check::ComplianceCheck`
///
/// `compliance_check::ComplianceCheck` (in `contracts/compliance-check`) is a
/// **plain Rust trait** — no XDR, no host functions, no `#[contractclient]`.
/// It is designed for compile-time composition: unit tests that import the
/// contract crate directly, generic helper functions (`fn check_all(impls...)`),
/// and in-process composition where you control the build.
///
/// This trait (`CrossContractComplianceCheck`) uses `#[contractclient]` and is
/// designed for the _opposite_ case: one **deployed** Soroban contract calling
/// another over XDR.  The two traits have the same method shape (`is_compliant`)
/// but serve entirely different layers of the stack and cannot substitute for
/// each other.
///
/// **Renamed from `ComplianceCheckInterface`** (issue #414) to make the
/// cross-contract / runtime nature explicit and reduce confusion with
/// `ComplianceCheck`.
///
/// `is_compliant` is declared only on this trait, so a client call resolves to
/// a single method; the interface traits below cover the primitive-specific
/// methods only.
#[contractclient(name = "CrossContractComplianceCheckClient")]
pub trait CrossContractComplianceCheck {
    fn is_compliant(env: Env, address: Address) -> bool;
}

/// `#[contractclient]`-backed interface for the `allowlist-token` contract.
///
/// Provides XDR-based client stubs for calling a deployed `allowlist-token`
/// contract from another Soroban contract or from off-chain tests via the
/// Soroban test harness.
#[contractclient(name = "AllowlistTokenClient")]
pub trait AllowlistTokenInterface {
    fn initialize(env: Env, admin: Address, token: Address);
    fn add_to_allowlist(env: Env, admin: Address, address: Address, expiration_ledger: Option<u32>);
    fn remove_from_allowlist(env: Env, admin: Address, address: Address);
    fn is_allowed(env: Env, address: Address) -> bool;
}

/// `#[contractclient]`-backed interface for the `denylist-gate` contract.
///
/// Provides XDR-based client stubs for calling a deployed `denylist-gate`
/// contract from another Soroban contract or from off-chain tests via the
/// Soroban test harness.
#[contractclient(name = "DenylistGateClient")]
pub trait DenylistGateInterface {
    fn initialize(env: Env, admin: Address);
    fn add_to_denylist(env: Env, admin: Address, address: Address);
    fn remove_from_denylist(env: Env, admin: Address, address: Address);
    fn check(env: Env, address: Address) -> bool;
}

/// `#[contractclient]`-backed interface for the `jurisdiction-flag` contract.
///
/// Provides XDR-based client stubs for calling a deployed `jurisdiction-flag`
/// contract from another Soroban contract or from off-chain tests via the
/// Soroban test harness.
#[contractclient(name = "JurisdictionFlagClient")]
pub trait JurisdictionFlagInterface {
    fn initialize(env: Env, issuer: Address);
    fn set_jurisdiction(env: Env, issuer: Address, address: Address, code: String);
    fn get_jurisdiction(env: Env, address: Address) -> Option<String>;
    fn is_permitted_jurisdiction(env: Env, address: Address, allowed_codes: soroban_sdk::Vec<String>) -> bool;
}

#[cfg(test)]
mod test;

#[cfg(test)]
mod policy_engine_test;
